
server:
  port: 8081

spring:
  application:
    name: order-service

  config:
    import: "env.properties"

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
